language: c

compiler: gcc

before_install:
    - sudo service postgresql stop
    - CURDIR=$(pwd)
    - PGHOME=${CURDIR}
    - PGDATA=${PGHOME}/data
    - mkdir ${PGDATA}
    - git clone https://github.com/postgres/postgres.git
    - cd postgres
    - ./configure --prefix=${PGHOME} --enable-debug --enable-cassert
    - make -j 2
    - make install
    - export PATH=${PATH}:${PGHOME}/bin
    - export LD_LIBRARY_PATH=${LD_LIBRAY_PATH}:${PGHOME}/lib
    - initdb -D ${PGDATA} --locale=C --encoding=UTF8
    - pg_ctl -D ${PGDATA} -w start

before_script:
    - cd ${CURDIR}
    - make USE_PGXS=1 PG_CONFIG=${PGHOME}/bin/pg_config
    - make USE_PGXS=1 PG_CONFIG=${PGHOME}/bin/pg_config install

script:
    - make USE_PGXS=1 PG_CONFIG=${PGHOME}/bin/pg_config installcheck

after_script:
    - if [ -f regression.diffs ]; then cat regression.diffs; fi
    - pg_ctl -D ${PGDATA} stop

notifications:
    email:
        on_success: change
        on_failure: always
